class Locators:
    USER_NAME = "//input[@name='username']"
    PASSWORD = "//input[@name='password']"
    LOGIN_BUTTON = "//button[@type='submit']"
    FORGOT_PASSWORD = "//button[@type='submit']"
    PIM_MODULE = "/html/body/div/div[1]/div[1]/aside/nav/div[2]/ul/li[2]/a/span"
    PIM_ADD_EMPLOYEES = "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[3]/a"
    PIM_FIRSTNAME = "//input[@name='firstName']"
    PIM_LASTNAME = "//input[@name='lastName']"
    PIM_SAVE = "/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[2]/button[2]"
    PIM_NICKNAME = "/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div[2]/div/div/div[2]/input"
    PIM_LICENSE = "/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div[2]/div[1]/div/div[2]/input"
    PIM_SCROLL = "/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[5]"
    PIM_PERSONAL_SAVE ="/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[5]/button"
    PIM_EXISTING_EMPLOYEE = "/html/body/div/div[1]/div[2]/div[2]/div/div[2]/div[3]/div/div[2]/div[1]/div/div[9]/div/button[2]/i"
    PIM_EXISTING_NICKNAME = "/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div[2]/div/div/div[2]/input"
    PIM_EXISTING_EMPLOYEE_SCROLL = "/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[5]"
    PIM_DELETE = "/html/body/div/div[1]/div[2]/div[2]/div/div[2]/div[3]/div/div[2]/div[1]/div/div[9]/div/button[1]/i"
    PIM_CONFIRM_DELETE = "/html/body/div/div[3]/div/div/div/div[3]/button[2]"
